development:
  adapter: mysql2
  user: root
  password: root
  database: housecall-consumer-web-development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  user: root
  password: root
  database: housecall-consumer-web-test
  pool: 5
  timeout: 5000

